### ISSUE TITLE
你好，能否写下使用文档呢，感谢

### ISSUE THREAD

**Issue by dalaoting** [duxiaofeng-github/TcPlayer#2]

**Comment by duxiaofeng-github** [comment]
使用文档请参考腾讯云播放器的文档：https://cloud.tencent.com/product/player。

这个库的文档，就是npm安装之后，从node_modules文件夹引入。

**Comment by duxiaofeng-github** [comment]
补了个example，https://github.com/duxiaofeng-github/TcPlayer/blob/master/docs
